### ISSUE TITLE
[New Project]: PDDL & Planning Group slack

### ISSUE THREAD

**Issue by nergmada** [nergmada/planning-wiki#41]
To help grow the community and provide better networking opportunities, we're launching a slack as part of this reference guide to provide a space for people to discuss and connect with planning.

[Join the slack group](https://join.slack.com/t/planningpddlgroup/shared_invite/enQtNjQyNDY0MTA0ODUyLTNlYWY3ODQ5ZTU0YWMyOGRiYzVmNmNlNjhmZThlZmU4MzQ0MTRlOTc1ZThmZjEyOWZjODBiMzEyYzg0MjIxNDc)

**Comment by nergmada** [comment]
@JonIsAmazingYa

**Comment by nergmada** [comment]
Hi @jan-dolejsi 
I realise you must be very busy but I just wanted to point this out, I'm currently in the process of launching a slack group for Planning & PDDL, hopefully this can be useful for yourself and your team. 

I really appreciate all of the support you've provided the guide so far, and I hope that this will help support it by bringing a more diverse knowledge base 

[here's the link](https://join.slack.com/t/planningpddlgroup/shared_invite/enQtNjQyNDY0MTA0ODUyLTNlYWY3ODQ5ZTU0YWMyOGRiYzVmNmNlNjhmZThlZmU4MzQ0MTRlOTc1ZThmZjEyOWZjODBiMzEyYzg0MjIxNDc)

**Comment by haz** [comment]
Just wanted to note on this issue that the slack group has shifted / unified to a pre-existing one. New signup: https://the-planning-community.herokuapp.com/

**Comment by jan-dolejsi** [comment]
Busy preparing demos for ICAPS 2019. Slack fits well into the venues where
people can connect with planning. I shall add a link to it on the vscode
extension.

Jan

**Comment by haz** [comment]
Aye, makes sense I think. It's the same slack pointed to from both the planning.wiki and slack.planning.domains . We could create a channel for our tutorial too.

**Comment by nergmada** [comment]
@jan-dolejsi I'm guessing because you follow the repo that you saw we've moved over to planning.wiki now for domain. The old domain still works, but this domain is better as the style and layout is much better suited to docs.

If you're planning on plugging the guide (which would be so amazing) please use planning.wiki
