### ISSUE TITLE
[New Content]: Web-Planner

### ISSUE THREAD

**Issue by Maumagnaguagno** [nergmada/planning-wiki#77]
New Content Proposal:
[Web-Planner](https://web-planner.herokuapp.com/)

Section:
Additional Resources

Justification:
Similar to Planning.domains, it is a planner in the cloud with editor, verification, validation and visualization capabilities.
The planner supports ``:strips``, ``:negative-preconditions``, ``:equality`` and ``:typing`` requirements.
For more information see the following papers from [ICAPS/UISP 2017](http://icaps17.icaps-conference.org/workshops/UISP/uisp17proceedings.pdf#page=36) and [ICAPS/Demos 2019](http://www.meneguzzi.eu/felipe/pubs/icaps-webplan-demo-2019.pdf).

Note:
I was not sure if a pull request would be better, as the Additional Resources page asked to fill an issue.

**Comment by nergmada** [comment]
Hi, can you please file a pull request with this information formatted using an existing planner page as a template. On 12 Aug 2020 23:57, Mau Magnaguagno <notifications@github.com> wrote:
New Content Proposal:
Web-Planner
Section:
Additional Resources
Justification:
Similar to Planning.domains, it is a planner in the cloud with editor, verification, validation and visualization capabilities.
For more information I have the following papers from ICAPS/UISP 2017 and ICAPS/Demos 2019.
The planner supports :strips, :negative-preconditions, :equality and :typing requirements.

**Comment by nergmada** [comment]
Hi @Maumagnaguagno have you had a chance to write a page for the web-planner?

**Comment by Maumagnaguagno** [comment]
Sorry, I did not have the time to do it yet :disappointed: 
I believe what you are looking for is something like the planners/name/main.md, such as this one from [FD](https://github.com/nergmada/planning-wiki/blob/master/docs/reference/planners/FD/main.md).
I will try to finish it today.

**Comment by nergmada** [comment]
Yeah, assuming it's just called web-planner it should be filed as 

`./planners/web-planner/main.md`
