### ISSUE TITLE
[New Content]:

### ISSUE THREAD

**Issue by bhomaidan1990** [nergmada/planning-wiki#97]
New Content Proposal:

Section:
Reference/Guide
PDDL/Planners

Justification:

These Planners Are not Listed in the A-Z list of Planners:

- [LiLotane](https://github.com/domschrei/lilotane)
- [PDDL4J](https://github.com/pellierd/pddl4j)

**Comment by nergmada** [comment]
LiLotane uses HDDL which we don't support documentation on yet. Feel free to open an issue and contribute changes for HDDL.

PDDL4J is a library - not a planner
