### ISSUE TITLE
How does my name come into this?

### ISSUE THREAD

**Issue by maltehelmert** [nergmada/planning-wiki#99]
Dear Adam,

the home page on https://planning.wiki/ starts with "Planning.Wiki - The AI Planning & PDDL Wiki -- [An] online compendium of planners and pddl material - Dr Malte Helmert". Several people have understood my name mentioned there as an indication of authorship for the wiki, so that I'd be the person that put it up there and that is responsible for the content. But I have nothing to do with the wiki, so this puts me in a very awkward position. Did you write this sentence? Can you remove it? If you wanted to communicate something other than authorship with my name there, I think it needs to be made clearer what that is. I don't feel comfortable with my name showing up on the page in the way it currently does, but if there is some other way I can help you out, let me know.

Best,
Malte

**Comment by nergmada** [comment]
Hi Malte,

Sorry this was a quote I was sent from a presentation you gave a couple of years ago, it should be quote marked on the sign and indented to quote it, but I'll remove it.

-Adam

**Comment by nergmada** [comment]
It should be removed now

-Adam
